### ISSUE TITLE
[meta] Kilas Balik Pengembang

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#221]
Sepertinya perlu mengumpulkan daftar episode kilas balik dalam satu tiket ini, para pengembang yang ingin mewawancarai siapa dapat ditulis di sini, termasuk episode yang sudah berlalu, tulis nomor tiket di akhir tiap barisnya:

- [ ] Episode 1 | @samsulmaarif mewawancarai pak Utian (#207)
- [ ] Episode 2 | pak @FaiqAminuddin mewawancarai pak @aftian (#220) 
- [ ] Episode 3 | siapa mewawancarai siapa
- [ ] Episode 4 | siapa mewawancarai siapa

**Comment by slamets75** [comment]
@samsulmaarif Saya mau wawancara Pak Ainul, Bu @umulsidikoh mau dengan Pak Rus ?

**Comment by samsulmaarif** [comment]
pak @slamets75 apakah sudah bikin jadwal dengan pak Ainul? bu @umulsidikoh jadi wawancara pak Rus ya?

**Comment by slamets75** [comment]
@samsulmaarif Belum Pak, baru mau kirim email.

**Comment by samsulmaarif** [comment]
pak @slamets75 sudah ada kabar dari pak Ainul?

**Comment by samsulmaarif** [comment]
pak @FaiqAminuddin jika ingin wawancara dengan pak Sokibi bisa langsung disiapkan & diagendakan saja pak

**Comment by samsulmaarif** [comment]
Terkait dengan kilas balik ini, pada rapat kemarin malam (15 Agustus 2021) saya mengusulkan agar ada seorang penanggung jawab/pengelola untuk menangani program ini sekaligus sebagai pewawancara utama. Bagi teman-teman yang berminat untuk menjadi pengelola silakan langsung ajukan diri melalui komentar di tiket ini.

**Comment by slamets75** [comment]
@samsulmaarif Izin mengambil tugas dan tanggung jawab sebagai PIC.

Mohon Bimbingan Pak-Bapak dan jajaran Tim di belakang. 🙏
