### ISSUE TITLE
Hidupkan kembali layanan yang ada di Rafi

### ISSUE THREAD

**Issue by samsulmaarif** [BlankOn/Verbeek#60]
Waljinah adalah peladen web www.blankonlinux.or.id dan beberapa layanan lain yang berbasis web.

- [x] kontak pic data center untuk waljinah
- [x] kunjungan lokasi jika diperlukan https://github.com/BlankOn/Verbeek/issues/74
- [x] pastikan waljinah dapat hidup kembali
- [x] ~~setup mesin baru (siluman)~~
- [x] ~~riset untuk memindahkan semua layanan yang ada di waljinah ke mesin siluman~~
- [x] ~~install ulang waljinah~~ Upgrade ke versi debian yang masih didukung security patch.
- [x] ~~kembalikan layanan ke mesin waljinah~~

Daftar layanan yang perlu dihidupkan (diusahakan untuk dimigrasikan ke container-based) kembali:

- [x] ~~1. aku.blankonlinux.or.id~~
- [x] 2. arsip.blankonlinux.or.id | sudah nyala di rani
- [x] 3. www.blankonlinux.or.id | redirect ke www.blankon.id
- [ ] 4. changelogs.blankonlinux.or.id 
- [x] ~~5. waljinah.blankonlinux.or.id~~ | pensiun
- [x] ~~6. waljinah.blankon.id~~ | pensiun
- [ ] 7. di.blankon.in | buat redirect ke blankon.id
- [ ] 8. www.blankon.in | buat redirect ke blankon.id
- [x] ~~9. ayo.semuanya.di.blankon.in~~ | konten berita telah dipindahkan ke https://blankon.id/berita/
- [x] ~~10. forum.blankonlinux.or.id~~
- [x] ~~11. i15n.blankonlinux.or.id~~
- [x] ~~12. irclog.blankon.in~~
- [x] 13. irgsh.blankonlinux.or.id | Rani
- [x] ~~14. p.blankon.in~~
- [x] ~~15. irgsh2.blankonlinux.or.id~~
- [ ] 16. konf.blankonlinux.or.id | redirect ke konf.blankon.id (#222)
- [ ] 17. konf2010.blankonlinux.or.id | redirect ke konf2010.blankon.id (#222)
- [ ] 18. konf2011.blankonlinux.or.id | redirect ke konf2011.blankon.id (#222)
- [ ] 19. konf2012.blankonlinux.or.id | redirect ke konf2012.blankon.id (#222)
- [x] 20. manokwari.blankonlinux.or.id | redirect ke manokwari.blankon.id
- [x] 21. sajadah.blankonlinux.or.id 
- [ ] 22. security.blankonlinux.or.id
- [x] 23. serambi.blankonlinux.or.id | sudah mengudara di serambi.blankon.id, belum dibuat redirect
- [x] ~~24. tempel.blankon.in~~
- [x] ~~25. w.blankon.in~~
- [x] ~~26. waw.bin~~
- [x] 27. panduan.boi (Eksekusi di #214)

**Comment by herpiko** [comment]
Berkas backup konfigurasi dan lain-lain sebelum upgrade ada di /home/backup_before_upgrade/. Mengenai pola nama,`var-lib-x_y_z` berarti `/var/lib/x_y_z`.

**Comment by herpiko** [comment]
Tambahan untuk serambi, https://github.com/BlankOn/Serambi/pull/10/files

**Comment by herpiko** [comment]
Prioritas unggah ke mesin baru:

- /home/situs
- Panduan.doi

**Comment by samsulmaarif** [comment]
pak @herpiko apakah sudah diunggah? ada di direktori mana di rafi? 

> Prioritas unggah ke mesin baru:
> 
>     * /home/situs
>     * Panduan.doi

**Comment by herpiko** [comment]
@samsulmaarif Belum pak, tapi hddnya sudah saya siapkan di PC. 

Saya nunggu rafi ok dulu, supaya pas unggah tidak terganggu operasi bapak di rafi.

**Comment by samsulmaarif** [comment]
Rafi sudah oke pak, silakan diunggah @herpiko

**Comment by herpiko** [comment]
Sudah terunggah di /home/herpiko/situs

**Comment by herpiko** [comment]
Btw ukurannya 25GB, kalau ada yang kurang mohon colek2.

**Comment by samsulmaarif** [comment]
pak @herpiko konten `/home/herpiko/situs` saya pindahin ke `/home/situs` ya pak. 

Oiya, saya belum menemukan dump basisdata (berkas .sql) untuk web panduan pak, lokasinya di mana ya?

**Comment by herpiko** [comment]
@samsulmaarif Saya coba carikan dulu pak.

**Comment by samsulmaarif** [comment]
Anggap sudah selesai, karena layanan inti pengembangan sudah berjalan. Jika bapak/ibu membutuhkan sesuatu terkait layanan ini boleh colek-colek tim Infra.
